# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '* */20 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Write the cypress.env.json file
    #   run: |
    #     echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
     
    - run: echo $CYPRESS_LOGIN
      env:
        CYPRESS_LOGIN: ${{ secrets.CYPRESS_LOGIN }}
    - run: npx cypress run --browser chrome --env login=$CYPRESS_LOGIN
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifacts
        path: |
          cypress/videos/
          cypress/screenshots/
          # cypress.env.json
